import argparse

from utils import get_index

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("dir", help="directory to parse", default=".")
    args = parser.parse_args()

    path = args.dir
    ignore = []
    _, output_update_list, ignore_count, err_count, user_et = get_index(path, ignore)

    print("# This file contains information about a fingerprint database.")
    print(
        "# It is intended to help when iterating over all images of a database."
    )
    print("#")
    print("#")
    print("# Database attributes:")
    print("## fingerIdsRegistered=0,1,2,3,4,5,6,7,8,9,10,11\n")
    print("## fingerTypesRegistered=0")
    print("## idFirstVerificationSample=1000")
    print("## idPersonBottom=1")
    print("## idPersonTop=66")
    print("## idSampleBottom=0")
    print("## idSampleTop=4000")
    print("## itemType=png")
    print("## locked=False")
    print("## name=A42")
    print("## resolution=705")
    print("# End of attributes")
    print("# This file was generated by: MixedFingers")
    print(
        "# The Python command that generated the fpdbindex can be found in the input file"
    )
    print("#")
    print("# Columns (tab separated):")
    print("# Person ID (0 if unknown)")
    print("# 	Finger ID (= Finger Type if unspecified or 0 if unknown/unused)")
    print("# 		Finger Type (according to ISO/IES 19794-2:2005 table 2)")
    print(
        "# 			Sample ID (sometimes referred to as \"Attempt\" or \"Transaction\")"
    )
    print("# 				Image file relative path")
    print("#")
    for i in range(len(output_update_list)):

        if output_update_list[i].find("_TRY_") >= 0:
            try_num = int(
                output_update_list[i][output_update_list[i].find("_TRY_") +
                                      5:output_update_list[i].find("_TRY_") +
                                        6])
            if try_num >= 0:
                print(output_update_list[i] +
                      " : verify_count={}".format(try_num))
        else:
            print(output_update_list[i])
        pass

    print("#len = {}".format(len(output_update_list)))
    print("#ignore_count = {}".format(ignore_count))
    print("#err_count = {}".format(err_count))
    print("#user_et = {}".format(user_et))
