import argparse
import os

from utils import parse_file_name, get_index

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("dir0", help="merged directory 0")
    parser.add_argument("dir1", help="merged directory 1")
    parser.add_argument("dir2", help="merged directory 2")
    parser.add_argument("filepath", help="output merged fpdbindex path", default="")
    parser.add_argument("-m", "--mode", type=int, help="learn mode", default=0)
    parser.add_argument("-ig", "--ignore", help="ignore key word, no need to match case", default="")
    parser.add_argument("-dpi", "--dpi", help="dpi setting", default="655")
    args = parser.parse_args()

    path0 = args.dir0
    path1 = args.dir1
    path2 = args.dir2
    filepath = args.filepath
    dpi = args.dpi
    path_root = os.path.dirname(filepath)
    filename = os.path.splitext(os.path.basename(filepath))[0]

    ign = args.ignore
    ignore = ign.split(',')
    for i in range(len(ignore)):
        if ignore[i] == "":
            ignore = []
            break

    # simulate
    sdk = 0
    try0_thresh = 80
    try1_thresh = 0
    try0_learning_thresh = 80
    try1_learning_thresh = 0  # change

    if args.mode == 0:  # sdk
        sdk = 1
        try0_thresh = 0
        try1_thresh = 0
        try0_learning_thresh = 80
        try1_learning_thresh = try0_learning_thresh  # 80
    elif args.mode == 1:  # full
        sdk = 0
        try0_thresh = 80
        try1_thresh = 0
        try0_learning_thresh = 80
        try1_learning_thresh = 0  # change

    list0, _, ignore_count0, err_count0, user_et0 = get_index(path0, ignore=ignore)
    list1, _, ignore_count1, err_count1, user_et1 = get_index(path1, ignore=ignore)
    list2, _, ignore_count2, err_count2, user_et2 = get_index(path2, ignore=ignore)

    print("#len0 = {}".format(len(list0)))
    print("#ignore_count0 = {}".format(ignore_count0))
    print("#err_count0 = {}".format(err_count0))
    print("#user_et0 = {}".format(user_et0))
    print("#len1 = {}".format(len(list1)))
    print("#ignore_count1 = {}".format(ignore_count1))
    print("#err_count1 = {}".format(err_count1))
    # print("#user_et1 = {}".format(user_et1))
    print("#len2 = {}".format(len(list2)))
    print("#ignore_count2 = {}".format(ignore_count2))
    print("#err_count2 = {}".format(err_count2))

    if path_root == "":
        folder1 = os.path.abspath(path1).split('\\')
        folder1 = folder1[len(folder1) - 1]
        folder2 = os.path.abspath(path2).split('\\')
        folder2 = folder2[len(folder2) - 1]
    else:
        folder0 = path0.replace(path_root, "")
        folder1 = path1.replace(path_root, "")
        folder2 = path2.replace(path_root, "")

    # remove \\ in front of folder path
    if folder0[0] == "\\":
        folder0 = folder0[1:]
    if folder1[0] == "\\":
        folder1 = folder1[1:]
    if folder2[0] == "\\":
        folder2 = folder2[1:]

    fp = open(filepath, "w")

    fp.write(
        "# This file contains information about a fingerprint database.\n")
    fp.write(
        "# It is intended to help when iterating over all images of a database.\n"
    )
    fp.write("#\n")
    fp.write("#\n")
    fp.write("# Database attributes:\n")
    fp.write("## fingerIdsRegistered=0,1,2,3,4,5,6,7,8,9,10,11\n")
    fp.write("## fingerTypesRegistered=0\n")
    fp.write("## idFirstVerificationSample=1000\n")
    fp.write("## idPersonBottom=1\n")
    fp.write("## idPersonTop=66\n")
    fp.write("## idSampleBottom=0\n")
    fp.write("## idSampleTop=4000\n")
    fp.write("## itemType=png\n")
    fp.write("## locked=False\n")
    fp.write("## name=" + filename + "\n")
    fp.write("## resolution={}\n".format(dpi))
    fp.write("# End of attributes\n")
    fp.write("# This file was generated by: MixedFingers\n")
    fp.write(
        "# The Python command that generated the fpdbindex can be found in the input file\n"
    )
    fp.write("#\n")
    fp.write("# Columns (tab separated):\n")
    fp.write("# Person ID (0 if unknown)\n")
    fp.write(
        "# 	Finger ID (= Finger Type if unspecified or 0 if unknown/unused)\n")
    fp.write("# 		Finger Type (according to ISO/IES 19794-2:2005 table 2)\n")
    fp.write(
        "# 			Sample ID (sometimes referred to as \"Attempt\" or \"Transaction\"\n"
    )
    fp.write("# 				Image file relative path\n")
    fp.write("#\n")

    count = 0
    verify_count = 0
    if len(list0) == len(list1) and len(list0) == len(list2):
        for i in range(len(list0)):
            log = parse_file_name(list0[i])

            info0, info1, info2, info3, info4 = list0[i].split('\t')
            info5, info6, info7, info8, info9 = list1[i].split('\t')
            info10, info11, info12, info13, info14 = list2[i].split('\t')

            if info4.find('20201002_142457_673') >= 0:
                print()
                pass

            # init count
            if int(info3) % 10000 == 0:
                count = int(info3)
            elif int(info3) == 0:
                count = 0

            if int(info3) < 1000:  # enroll
                output0 = "{0}\t{1}\t{2}\t{3}\t{4}".format(
                    info0, info1, info2, count, folder0 + '\\' + info4 + "\n")
                count += 1
                fp.write(output0)
                # output1 = "{0}\t{1}\t{2}\t{3}\t{4}".format( info0, info1, info2, count, folder1 + '\\' + info9 + "\n")
                # count += 1
                # fp.write(output1)
            else:
                output0 = "{0}\t{1}\t{2}\t{3}\t{4}".format(
                    info0, info1, info2, count, folder0 + '\\' + info4)
                count += 1
                output1 = "{0}\t{1}\t{2}\t{3}\t{4}".format(
                    info0, info1, info2, count, folder1 + '\\' + info9)
                count += 1
                output2 = "{0}\t{1}\t{2}\t{3}\t{4}".format(
                    info10, info11, info12, count, folder2 + '\\' + info14)
                count += 1

                if info4.find("_TRY_") >= 0:
                    try_num = int(info4[info4.find("_TRY_") + 5:info4.find("_TRY_") + 6])
                    if try_num == 0:
                        verify_count = 0
                    else:
                        verify_count += 3
                elif info4.find("_pass_") >= 0:
                    try_num = int(info4[info4.find("_pass_") + 6:info4.find("_pass_") + 7])
                    if try_num == 0:
                        verify_count = 0
                    else:
                        verify_count += 3
                elif info4.find("_fail_") >= 0:
                    try_num = int(info4[info4.find("_fail_") + 6:info4.find("_fail_") + 7])
                    if try_num == 0:
                        verify_count = 0
                    else:
                        verify_count += 3

                if log.dict['egp'] == 'None':
                    fp.write(output0 + " : verify_count={}\n".format(verify_count))
                    fp.write(output1 + " : verify_count={}\n".format(verify_count + 1))
                    fp.write(output2 + " : verify_count={}\n".format(verify_count + 2))
                elif log.dict['irl'] == 'None' or log.dict[
                    'rls'] == 'None' or log.dict['sl'] == 'None':
                    if int(log.dict['egp']) >= try0_thresh:
                        if int(log.dict['egp']) >= try0_learning_thresh:
                            fp.write(output0 + " : verify_count={}\n".format(verify_count))
                        else:
                            fp.write(output0 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                        if int(log.dict['egp']) >= try1_thresh:
                            if int(log.dict['egp']) >= try1_learning_thresh:
                                fp.write(output1 + " : verify_count={}\n".format(verify_count + 1))
                                fp.write(output2 + " : verify_count={}\n".format(verify_count + 2))
                            else:
                                fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                                fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 2))
                    elif int(log.dict['egp']) >= try1_thresh:
                        if int(log.dict['egp']) >= try1_learning_thresh:
                            fp.write(output1 + " : verify_count={}\n".format(verify_count))
                            fp.write(output2 + " : verify_count={}\n".format(verify_count + 1))
                        else:
                            fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                            fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                        verify_count -= 1
                else:
                    if int(log.dict['irl']) > 0 and (int(log.dict['rls']) > 50 or int(log.dict['sl']) > 90):
                        if sdk == 1:
                            fp.write(output0 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                            fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                            fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 2))
                        else:
                            if int(log.dict['egp']) >= try1_learning_thresh:
                                fp.write(output1 + " : verify_count={}\n".format(verify_count))
                                fp.write(output2 + " : verify_count={}\n".format(verify_count + 1))
                            else:
                                fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                                fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                            verify_count -= 1
                    elif int(log.dict['egp']) >= try0_thresh:
                        if int(log.dict['egp']) >= try0_learning_thresh:
                            fp.write(output0 + " : verify_count={}\n".format(verify_count))
                        else:
                            fp.write(output0 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                        if int(log.dict['egp']) >= try1_thresh:
                            if int(log.dict['egp']) >= try1_learning_thresh:
                                fp.write(output1 + " : verify_count={}\n".format(verify_count + 1))
                                fp.write(output2 + " : verify_count={}\n".format(verify_count + 2))
                            else:
                                fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                                fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 2))
                    elif int(log.dict['egp']) >= try1_thresh:
                        if int(log.dict['egp']) >= try1_learning_thresh:
                            fp.write(output1 + " : verify_count={}\n".format(verify_count))
                            fp.write(output2 + " : verify_count={}\n".format(verify_count + 1))
                        else:
                            fp.write(output1 + " : verify_count={} skip_dyn_update\n".format(verify_count))
                            fp.write(output2 + " : verify_count={} skip_dyn_update\n".format(verify_count + 1))
                        verify_count -= 1

    else:
        print("len(list0) {} != len(list1) {} or != len(list1) {}".format(len(list0), len(list1), len(list2)))
    pass

    fp.close()
